apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: wine-kube-config
      protocol: layer2
      addresses:
      - 10.10.10.50-10.10.10.99
